// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsV-rdatW_yQw1ygBtuG8Bpl4D6x97Lt8',
    appId: '1:618949621645:web:ced64bc094a3b6ac66afc4',
    messagingSenderId: '618949621645',
    projectId: 'hosteldelivery-a1f63',
    authDomain: 'hosteldelivery-a1f63.firebaseapp.com',
    storageBucket: 'hosteldelivery-a1f63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-qbLCXphZ9V07mDYNIm0iu7gSAve6d0',
    appId: '1:618949621645:android:75e62c010d655b9c66afc4',
    messagingSenderId: '618949621645',
    projectId: 'hosteldelivery-a1f63',
    storageBucket: 'hosteldelivery-a1f63.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA37GW7_NQ8o53GdFh1PXJYzyrASw9GiU',
    appId: '1:618949621645:ios:3e591d0c7844f1ef66afc4',
    messagingSenderId: '618949621645',
    projectId: 'hosteldelivery-a1f63',
    storageBucket: 'hosteldelivery-a1f63.firebasestorage.app',
    androidClientId: '618949621645-ns5620o17fp4aqlfaksjjama9v77snog.apps.googleusercontent.com',
    iosClientId: '618949621645-oll3r253h67lonf318qbtjkgrmpnoem7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelDelivery',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA37GW7_NQ8o53GdFh1PXJYzyrASw9GiU',
    appId: '1:618949621645:ios:3e591d0c7844f1ef66afc4',
    messagingSenderId: '618949621645',
    projectId: 'hosteldelivery-a1f63',
    storageBucket: 'hosteldelivery-a1f63.firebasestorage.app',
    androidClientId: '618949621645-ns5620o17fp4aqlfaksjjama9v77snog.apps.googleusercontent.com',
    iosClientId: '618949621645-oll3r253h67lonf318qbtjkgrmpnoem7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsV-rdatW_yQw1ygBtuG8Bpl4D6x97Lt8',
    appId: '1:618949621645:web:65a43f0ac138c62766afc4',
    messagingSenderId: '618949621645',
    projectId: 'hosteldelivery-a1f63',
    authDomain: 'hosteldelivery-a1f63.firebaseapp.com',
    storageBucket: 'hosteldelivery-a1f63.firebasestorage.app',
  );
}
